version:     "14-Sep-2021"
copyright:   "2021-2021"
description:
  This is a
  GitHub Page Template
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Log"
  link:      "https://fathanm10.github.io/os212/TXT/mylog.txt"
- navbar:    "Key"
  link:      "https://fathanm10.github.io/os212/TXT/mypubkey.txt"
- navbar:    "GitHub"
  link:      "https://github.com/fathanm10/os212"
- navbar:    "Rank"
  link:      "https://fathanm10.github.io/os212/TXT/myrank.txt"
title:       "fathanm10's GitHub Page"
lang:        "en-US"
author:      "fathanm10"
address:     "Operating Systems 2021-2"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://fathanm10.github.io/os212/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/fathanm10/os212"


